<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Apaekshits_PC" failures="1" tests="5" name="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" time="66.929" errors="0" timestamp="2024-07-19T15:34:08 IST" skipped="2">
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="OrderHistory" time="5.389">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest.OrderHistory(SubmitOrderTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- OrderHistory -->
  <system-out/>
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="13.481">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <system-out/>
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="16.221"/>
  <system-out/>
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="14.374">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <system-out/>
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="17.464"/>
  <system-out/>
</testsuite> <!-- Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest -->
