<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Apaekshits_PC" failures="1" tests="4" name="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" time="56.290" errors="0" timestamp="2024-07-19T15:41:21 IST" skipped="1">
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="OrderHistory" time="4.483">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest.OrderHistory(SubmitOrderTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- OrderHistory -->
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="15.702">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="18.295"/>
  <testcase classname="Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest" name="submitOrder" time="17.810"/>
</testsuite> <!-- Apaekshit_Autoamtion.AutomationEnterpriseLevelFramework.SubmitOrderTest -->
